### ISSUE TITLE
Conditional variable initialisation in `AmiciObjective.check_gradients_match_finite_differences`

### ISSUE THREAD

**Issue by m-philipps** [ICB-DCM/pyPESTO#1494]
Gradient check for an `AmiciObjective`
```python
pypesto_problem.objective.check_gradients_match_finite_differences(
        x=startpoints[0],
    )
```
invokes an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maren/pyPESTO/pypesto/objective/amici/amici.py", line 665, in check_gradients_match_finite_differences
    *args, x=x, x_free=x_free, **kwargs
                       ^^^^^^
UnboundLocalError: cannot access local variable 'x_free' where it is not associated with a value
```

This is because `x_free` is only created if the condition in [line 651](https://github.com/ICB-DCM/pyPESTO/blob/ead29b36db80d2eeee91b5d29bfbf4430137f8aa/pypesto/objective/amici/amici.py#L651) is `True`. 

Version `0.5.1`

**Comment by m-philipps** [comment]
Is there a point to inheriting the `check_gradients_match_finite_differences` in the scope of `AmiciObjective.` at all? Using the PEtab nominal parameter vector is only used for testing and that default behaviour should at least be documented.

**Comment by m-philipps** [comment]
Linked to https://github.com/ICB-DCM/pyPESTO/issues/723

**Comment by dweindl** [comment]
> Is there a point to inheriting the `check_gradients_match_finite_differences` in the scope of `AmiciObjective.` at all? Using the PEtab nominal parameter vector is only used for testing and that default behaviour should at least be documented.

From my point of view, this could be removed completely. There is no clear understanding of what should be given as nominal parameter, but most often this will be the optimized parameters, which is not the best location for the finite difference checks due to vanishing gradients.

**Comment by PaulJonasJost** [comment]
closing this for now, due to new release
