### ISSUE TITLE
Calling pyPESTO objective with sensi_orders=(0,1) fails when using adjoints

### ISSUE THREAD

**Issue by LeonardSchmiester** [ICB-DCM/pyPESTO#193]
When running:
```
importer = pypesto.PetabImporter(petab_problem)
obj = importer.create_objective()
obj.amici_solver.setSensitivityMethod(2)
obj(petab_problem.x_nominal, sensi_orders=(0,1))
```
I get the error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/icb/leonard.schmiester/anaconda3/envs/speedy5/lib/python3.7/site-packages/pypesto/objective/objective.py", line 219, in __call__
    result = self._call_unprocessed(x, sensi_orders, mode)
  File "/home/icb/leonard.schmiester/anaconda3/envs/speedy5/lib/python3.7/site-packages/pypesto/objective/objective.py", line 239, in _call_unprocessed
    result = self._call_mode_fun(x, sensi_orders)
  File "/home/icb/leonard.schmiester/anaconda3/envs/speedy5/lib/python3.7/site-packages/pypesto/objective/objective.py", line 251, in _call_mode_fun
    result = self.fun(x, sensi_orders)
  File "/home/icb/leonard.schmiester/anaconda3/envs/speedy5/lib/python3.7/site-packages/pypesto/objective/amici_objective.py", line 193, in fun
    return self._call_amici(x, sensi_orders, MODE_FUN)
  File "/home/icb/leonard.schmiester/anaconda3/envs/speedy5/lib/python3.7/site-packages/pypesto/objective/amici_objective.py", line 316, in _call_amici
    coefficient=-1.0
  File "/home/icb/leonard.schmiester/anaconda3/envs/speedy5/lib/python3.7/site-packages/pypesto/objective/amici_objective.py", line 675, in add_sim_hess_to_opt_hess
    coefficient * sim_hess[par_sim_idx, par_sim_idx_2]
TypeError: 'NoneType' object is not subscriptable
```

Adding `if sensi_order > 1` in line 309 of the `amici_objective` should fix this issue I think

**Comment by yannikschaelte** [comment]
in that case, s2nllh would stay zero, but I wouldn't see a problem with that, since it is not used anyway. so your fix should work I think, and possibly save some computation time.
