### ISSUE TITLE
Dimension missmatch in apply_steadystate_guess

### ISSUE THREAD

**Issue by LeonardSchmiester** [ICB-DCM/pyPESTO#211]
I tried to evaluate the objective function of the `Weber_BMC2015` model with the nominal parameters and get the error message:
```
Traceback (most recent call last):
  File "/home/leonard/Documents/projects/benchmark_collection/optimizeBenchmarkModels.py", line 33, in <module>
    [obj(petab_problem.x_nominal_scaled, sensi_orders=(0, 1)) for idx in range(2)]
  File "/home/leonard/Documents/projects/benchmark_collection/optimizeBenchmarkModels.py", line 33, in <listcomp>
    [obj(petab_problem.x_nominal_scaled, sensi_orders=(0, 1)) for idx in range(2)]
  File "/home/leonard/Anaconda/envs/benchmark_collection/lib/python3.7/site-packages/pypesto/objective/objective.py", line 233, in __call__
    result = self._call_unprocessed(x, sensi_orders, mode)
  File "/home/leonard/Anaconda/envs/benchmark_collection/lib/python3.7/site-packages/pypesto/objective/objective.py", line 253, in _call_unprocessed
    result = self._call_mode_fun(x, sensi_orders)
  File "/home/leonard/Anaconda/envs/benchmark_collection/lib/python3.7/site-packages/pypesto/objective/objective.py", line 265, in _call_mode_fun
    result = self.fun(x, sensi_orders)
  File "/home/leonard/Anaconda/envs/benchmark_collection/lib/python3.7/site-packages/pypesto/objective/amici_objective.py", line 192, in fun
    return self._call_amici(x, sensi_orders, MODE_FUN)
  File "/home/leonard/Anaconda/envs/benchmark_collection/lib/python3.7/site-packages/pypesto/objective/amici_objective.py", line 282, in _call_amici
    self.apply_steadystate_guess(data_ix, x)
  File "/home/leonard/Anaconda/envs/benchmark_collection/lib/python3.7/site-packages/pypesto/objective/amici_objective.py", line 440, in apply_steadystate_guess
    (x_sim - guess_data['x'])
ValueError: shapes (7,36) and (40,) not aligned: 36 (dim 1) != 40 (dim 0)
```

I'm using the `feature_207_petab` branch of pyPESTO and the `develop` branch of PEtab.

**Comment by yannikschaelte** [comment]
@LeonardSchmiester Can you check it this is still a problem with the latest versions of everything?

**Comment by LeonardSchmiester** [comment]
It seems to work now. Get tons of amici warnings for failed simulations, but the bug is resolved. Will close this issue.

**Comment by yannikschaelte** [comment]
About the amici warnings ... definitely something to keep in mind, but I think those always existed ...
