### ISSUE TITLE
Optimization crashes for ls_trf and ls_dogbox if simulation fails

### ISSUE THREAD

**Issue by LeonardSchmiester** [ICB-DCM/pyPESTO#280]
If for one start, one simulation fails and returns a NaN / inf objective function value for the least squares optimizers `ls_trf` and `ls_dogbox`, the whole optimization crashes (for `ls_trf`):

```
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/pypesto/optimize/optimize.py", line 109, in minimize
    ret = engine.execute(tasks)
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/pypesto/engine/single_core.py", line 22, in execute
    results.append(task.execute())
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/pypesto/engine/task.py", line 78, in execute
    optimizer_result = self.optimizer.minimize(
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/pypesto/optimize/optimizer.py", line 88, in wrapped_minimize
    result = minimize(self, problem, x0, id, history_options)
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/pypesto/optimize/optimizer.py", line 72, in wrapped_minimize
    result = minimize(self, problem, x0, id, history_options)
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/pypesto/optimize/optimizer.py", line 52, in wrapped_minimize
    result = minimize(self, problem, x0, id, history_options)
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/pypesto/optimize/optimizer.py", line 270, in minimize
    res = scipy.optimize.least_squares(
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/scipy/optimize/_lsq/least_squares.py", line 915, in least_squares
    result = trf(fun_wrapped, jac_wrapped, x0, f0, J0, lb, ub, ftol, xtol,
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/scipy/optimize/_lsq/trf.py", line 126, in trf
    return trf_bounds(
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/scipy/optimize/_lsq/trf.py", line 304, in trf_bounds
    U, s, V = svd(J_augmented, full_matrices=False)
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/scipy/linalg/decomp_svd.py", line 109, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/scipy/_lib/_util.py", line 246, in _asarray_validated
    a = toarray(a)
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/numpy/lib/function_base.py", line 498, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs
```

and for `ls_dogox`:
```
ERROR:root:An exception was thrown!
Traceback (most recent call last):
  File "/home/leonard/Documents/projects/optimizer_benchmark/optimizer_benchmark/optimize_all.py", line 61, in <module>
    result = pypesto.minimize(problem=problem, optimizer=optimizer, n_starts=n_starts, engine=engine)
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/pypesto/optimize/optimize.py", line 109, in minimize
    ret = engine.execute(tasks)
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/pypesto/engine/single_core.py", line 22, in execute
    results.append(task.execute())

Given the residuals f(x) (an m-dimensional real function of n real variables) and the loss function rho(s) (a scalar function), least_squares finds a local minimum of the cost function F(x):

minimize F(x) = 0.5 * sum(rho(f_i(x)**2), i = 0, ..., m - 1)
subject to lb <= x <= ub


  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/pypesto/engine/task.py", line 78, in execute
    optimizer_result = self.optimizer.minimize(
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/pypesto/optimize/optimizer.py", line 88, in wrapped_minimize
    result = minimize(self, problem, x0, id, history_options)
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/pypesto/optimize/optimizer.py", line 72, in wrapped_minimize
    result = minimize(self, problem, x0, id, history_options)
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/pypesto/optimize/optimizer.py", line 52, in wrapped_minimize
    result = minimize(self, problem, x0, id, history_options)
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/pypesto/optimize/optimizer.py", line 270, in minimize
    res = scipy.optimize.least_squares(
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/scipy/optimize/_lsq/least_squares.py", line 926, in least_squares
    result = dogbox(fun_wrapped, jac_wrapped, x0, f0, J0, lb, ub, ftol,
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/scipy/optimize/_lsq/dogbox.py", line 225, in dogbox
    newton_step = lstsq(J_free, -f, rcond=-1)[0]
  File "<__array_function__ internals>", line 5, in lstsq
  File "/home/leonard/Anaconda/envs/optimizer_benchmark/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 2259, in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
ValueError: On entry to DLASCL parameter number 4 had an illegal value
```

I guess it would be better to still continue with the other starts.

**Comment by yannikschaelte** [comment]
there is an option 'allow_failed_starts' in the optimizer options. does that help?

**Comment by JanHasenauer** [comment]
should the 'allow_failed_starts' by true by default? might be good as this happens regularly

**Comment by LeonardSchmiester** [comment]
> there is an option 'allow_failed_starts' in the optimizer options. does that help?

Thanks. That seems to work.

> should the 'allow_failed_starts' by true by default? might be good as this happens regularly

Fully agreed.

**Comment by yannikschaelte** [comment]
agreed, let's make it default.
