### ISSUE TITLE
pypesto.minimize failed using the MultiProcessEngine

### ISSUE THREAD

**Issue by stobiblum** [ICB-DCM/pyPESTO#391]
Hey,

I tried simulating the "Boehm_JProteomeRes2014" benchmark model following the petab_import.ipynb.
I used pypesto version 0.0.13, amici version 011.1 and petab 0.1.7 version on WSL.

Using the `MultiProcessEngine` produced the following error for `result =pypesto.minimize(problem=problem, optimizer=optimizer, n_starts=10, engine=engine)`:
```
Traceback (most recent call last):
File "boehm.py", line 93, in <module> result = pypesto.minimize(problem=problem, optimizer=optimizer,
File "/home/tblum/developversion/pyPESTO/pypesto/optimize/optimize.py", line 109, in minimize ret = engine.execute(tasks)
File "/home/tblum/developversion/pyPESTO/pypesto/engine/multi_process.py", line 49, in execute pickled_tasks = [pickle.dumps(task) for task in tasks]
File "/home/tblum/developversion/pyPESTO/pypesto/engine/multi_process.py", line 49, in <listcomp> pickled_tasks = [pickle.dumps(task) for task in tasks]
File "/home/tblum/.local/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 63, in dumps cp.dump(obj)
File "/home/tblum/.local/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 548, in dump return Pickler.dump(self, obj)
File "/home/tblum/developversion/pyPESTO/pypesto/objective/amici_objective.py", line 275, in __getstate__ amici.writeSolverSettingsToHDF5(self.amici_solver, amici_solver_file)
File "/home/tblum/developversion/AMICI/python/sdist/amici/__init__.py", line 264, in writeSolverSettingsToHDF5 amici.writeSolverSettingsToHDF5(solver.get(), file, location)
AttributeError: module 'amici.amici_without_hdf5' has no attribute 'writeSolverSettingsToHDF5'
```

Using the `SingleCoreEngine` instead worked fine.

It also occurs with the develop branches of amici, pypesto and petab.

**Comment by dweindl** [comment]
> AttributeError: module 'amici.amici_without_hdf5' has no attribute 'writeSolverSettingsToHDF5'

This happens if AMICI was built without HDF5 support. Which is the case for most users I think. Wasn't aware that this functionality was used in pyPESTO.

So in your specific case, you could build AMICI with HDF5 support. When using WSL/Ubuntu, this would be `apt install libhdf5-serial-dev` and reinstalling AMICI.

Overall, I am not sure if things should be kept like that in pyPESTO, or whether we want to use a custom h5py-based implementation or implement some `amici::Solver::settings_to_yaml`.

**Comment by yannikschaelte** [comment]
Right, saving settings is currently required for serialization (which the MultiProcessEngine uses). 

@dweindl I would be happy if there is a way in AMICI to store settings to e.g. yaml instead of hdf5, this was just the most straightforward thing to implement atm, as one would otherwise need to keep track of copying all settings object attributes to the various file formats.

**Comment by dweindl** [comment]
> I would be happy if there is a way in AMICI to store settings

The major problem there is that this means reimplementing some json/yaml/whatever parser or introducing additional dependencies in AMICI. Turned out that already swig and cblas made it rather difficult to keep things simple and portable... 
In fact, there is already serialization support for `Model` and `Solver` settings in AMICI, but not included in the python package for the aforementioned reason.
