### ISSUE TITLE
Installation on python 3.9 fails: llvmlite

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyPESTO#575]
Error message:

```python
 Building wheel for llvmlite (setup.py): started
  Building wheel for llvmlite (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/hostedtoolcache/Python/3.9.1/x64/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-m3tn__px/llvmlite_3f808f7c3a774833b959d4683005a58c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-m3tn__px/llvmlite_3f808f7c3a774833b959d4683005a58c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-2lstkexx
  Running setup.py clean for llvmlite
       cwd: /tmp/pip-install-m3tn__px/llvmlite_3f808f7c3a774833b959d4683005a58c/
  Complete output (26 lines):
  running bdist_wheel
  /opt/hostedtoolcache/Python/3.9.1/x64/bin/python /tmp/pip-install-m3tn__px/llvmlite_3f808f7c3a774833b959d4683005a58c/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-m3tn__px/llvmlite_3f808f7c3a774833b959d4683005a58c/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/subprocess.py", line 501, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/subprocess.py", line 947, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/subprocess.py", line 1819, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
```

**Comment by yannikschaelte** [comment]
done in 0.2.5
