### ISSUE TITLE
Error optimizing with AMICI 0.11.16

### ISSUE THREAD

**Issue by dilpath** [ICB-DCM/pyPESTO#643]
Same code as #642 fails with the following traceback, with AMICI 0.11.16. No such error with AMICI 0.11.15, which is used in #642.
```bash
bash mkenv.sh
source venv_bug2/bin/activate
python bug.py
```

```
Traceback (most recent call last):
  File "bug.py", line 64, in <module>
    pypesto_result = pypesto.optimize.minimize(
  File "pypesto/optimize/optimize.py", line 113, in minimize
    ret = engine.execute(tasks)
  File "pypesto/engine/single_core.py", line 22, in execute
    results.append(task.execute())
  File "pypesto/optimize/task.py", line 55, in execute
    optimizer_result = self.optimizer.minimize(
  File "pypesto/optimize/optimizer.py", line 127, in wrapped_minimize
    result = minimize(self, problem, x0, id, allow_failed_starts,
  File "pypesto/optimize/optimizer.py", line 108, in wrapped_minimize
    result = minimize(self, problem, x0, id, allow_failed_starts,
  File "pypesto/optimize/optimizer.py", line 77, in wrapped_minimize
    result = minimize(self, problem, x0, id, history_options)
  File "pypesto/optimize/optimizer.py", line 398, in minimize
    res = scipy.optimize.minimize(
  File "scipy/optimize/_minimize.py", line 619, in minimize
    return _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "scipy/optimize/lbfgsb.py", line 306, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
  File "scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "scipy/optimize/_differentiable_functions.py", line 155, in __init__
    self._update_grad()
  File "scipy/optimize/_differentiable_functions.py", line 231, in _update_grad
    self._update_grad_impl()
  File "scipy/optimize/_differentiable_functions.py", line 145, in update_grad
    self.g = grad_wrapped(self.x)
  File "scipy/optimize/_differentiable_functions.py", line 142, in grad_wrapped
    return np.atleast_1d(grad(x, *args))
  File "pypesto/objective/base.py", line 265, in get_grad
    grad = self(x, (1,), MODE_FUN)
  File "pypesto/objective/base.py", line 146, in __call__
    result = self.call_unprocessed(x_full, sensi_orders, mode, **kwargs)
  File "pypesto/objective/amici.py", line 316, in call_unprocessed
    ret = self.calculator(
  File "pypesto/objective/amici_calculator.py", line 112, in __call__
    return calculate_function_values(
  File "pypesto/objective/amici_calculator.py", line 159, in calculate_function_values
    add_sim_grad_to_opt_grad(
  File "pypesto/objective/amici_util.py", line 183, in add_sim_grad_to_opt_grad
    coefficient * sim_grad[par_sim_slice[unique_index]]
IndexError: index 7 is out of bounds for axis 0 with size 7
```

**Comment by dweindl** [comment]
Without having had a closer look: Probably related to https://github.com/AMICI-dev/AMICI/pull/1487 & https://github.com/AMICI-dev/AMICI/pull/1488

**Comment by FFroehlich** [comment]
This should already be fixed on develop. Maybe a good idea to push releases more regularly.

**Comment by dilpath** [comment]
> This should already be fixed on develop. Maybe a good idea to push releases more regularly.

Thanks, confirmed fixed on develop, should have checked.

**Comment by jvanhoefer** [comment]
@dilpath This is closed with the new release, right? (otherwise please reopen :) )
