### ISSUE TITLE
ValueError:Steadystate prediciton is not supported formodels with conservation laws! in PyCharm

### ISSUE THREAD

**Issue by harshitaojha** [ICB-DCM/pyPESTO#698]
While replicating the Lotka-Volterra model in pycharm, I am getting error at this point:
Traceback (most recent call last):
  File "/home/harshita/PycharmProjects/Project_ICL_lotkaVolterra/yaml_2_petab.py", line 27, in <module>
    problem = importer.create_problem()
  File "/home/harshita/anaconda3/envs/Project_ICL_lotkaVolterra/lib/python3.9/site-packages/pypesto/petab/importer.py", line 288, in create_problem
    objective = self.create_objective(**kwargs)
  File "/home/harshita/anaconda3/envs/Project_ICL_lotkaVolterra/lib/python3.9/site-packages/pypesto/petab/importer.py", line 260, in create_objective
    obj = AmiciObjective(
  File "/home/harshita/anaconda3/envs/Project_ICL_lotkaVolterra/lib/python3.9/site-packages/pypesto/objective/amici_objective.py", line 173, in __init__
    raise ValueError('Steadystate prediciton is not supported for'
ValueError: Steadystate prediciton is not supported formodels with conservation laws!

**Comment by dweindl** [comment]
Hi @harshitaojha,

> File "/home/harshita/anaconda3/envs/Project_ICL_lotkaVolterra/lib/python3.9/site-packages/pypesto/objective/amici_objective.py",

It seems you are using a rather old version of pypesto (this file has been [(re)moved](https://github.com/ICB-DCM/pyPESTO/compare/v0.0.13...v0.1.0) about a year ago). Please retry with the current version of pypesto.

**Comment by harshitaojha** [comment]
Thanks a lot, it worked:)
