### ISSUE TITLE
`pypesto.Problem()` cannot be created when using finite differences for gradient and custom objective function

### ISSUE THREAD

**Issue by vanako** [ICB-DCM/pyPESTO#716]
I would like to fit a model for which I implemented a custom objective function which does not return a gradient. That is why I'd like to use `pypesto.objective.FD(objective_fun)` for gradient calculation. However, when the problem is created, an error is returned. There seems to be an issue when copying the Objective object. I attached a small example [here](https://github.com/ICB-DCM/pyPESTO/files/6900917/deepcopy_bug_mwe.txt).
Thanks for your help!
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-e7c8165c4ecc>", line 1, in <module>
    problem = pypesto.Problem(objective=custom_objective,
  File "/python3.9/site-packages/pypesto/problem.py", line 99, in __init__
    self.objective = copy.deepcopy(objective)
  File "/usr/lib/python3.9/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/python3.9/site-packages/pypesto/objective/base.py", line 57, in __deepcopy__
    other = type(self)()  # maintain type for derived classes
TypeError: __init__() missing 1 required positional argument: 'obj'
```

**Comment by jvanhoefer** [comment]
Seems to be already resolved in the current `develop` branch :)
